server:
  port: 8085
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
hm:
  db:
    database: hm-trade
  swagger:
    title: "黑马商城交易服务接口文档"
    package: com.hmall.trade.controller
spring:
  rabbitmq:
    host: 115.190.39.160
    port: 5672
    virtual-host: /hmall
    username: hmall
    password: 123