server:
  port: 8084
spring:
  application:
    name: user-service
feign:
  okhttp:
    enabled: true # 开启OKHttp功能
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  db:
    database: hm-user
  swagger:
    title: "黑马商城用户接口文档"
    package: com.hmall.user.controller